workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    instance_type: linux

    environment:
      node: 18
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web app
        script: |
          npm run build

      - name: Ensure Android platform
        script: |
          npx cap add android || true

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
